FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime

RUN apt-get update && apt-get install -y git curl

RUN pip install --upgrade pip
RUN pip install text-generation

WORKDIR /app

EXPOSE 5560

CMD ["text-generation-launcher", "--model-id", "./model", "--host", "0.0.0.0", "--port", "5560", "--num-gpu", "1"]
