# Stage 1: Build the Angular application
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve the application
FROM node:20-alpine

WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=build /app/dist/Chat.Frontend/browser ./browser
COPY --from=build /app/dist/Chat.Frontend/server ./server

# Install production dependencies for the server
# COPY package.json package-lock.json ./
# RUN npm install --only=production

EXPOSE 80

CMD ["node", "server/server.mjs"]
